### PR TITLE
implement py-mutable-immutable

### PR DESCRIPTION
**Pull request by daikj88**

### CODE REVIEW

**Comment by Hulk-hurry-Hulk-smash** [comment]
added a comment here

**Comment by Ngayka** [comment]
add dictionary for mutable/immutable types

**Comment by valantisq10** [comment]
Sorting variables into mutable and immutable categories

**Comment by mrsugarr** [comment]
mutable immutable types

**Comment by mrsugarr** [comment]
solution

**Comment by mhrabovska** [comment]
This script organizes variables into mutable and immutable categories, populating the sorted_variables dictionary as required.

**Comment by mhrabovska** [comment]
Updated variables, added films, modified dictionary

**Comment by mhrabovska** [comment]
Bugs fixed, variables sorted correctly, all tests pass

**Comment by DragmAik** [comment]
Sorting mutable and immutable data types.

**Comment by DragmAik** [comment]
Sorting mutable and immutable data types.

**Comment by Sashazmei** [comment]
mate-academy:master и Sashazmei:master идентичны.

**Comment by Sashazmei** [comment]
do

**Comment by cnlgstcorp** [comment]
ready

**Comment by pewlay** [comment]
ready

**Comment by ArtemH19** [comment]
.

**Comment by Syai-san** [comment]
add dictionary for mutable/immutable types

**Comment by stephanysantana05** [comment]
Mate Academy

**Comment by iago0411** [comment]
solution

**Pull request closed without merging**
